name = "[LRPG] ZEI"
author = "[LRPG] Young"
mainprefix = "lrpg"
prefix = "zei"

[files]
include = [
    "data/zeus.paa"
]

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "583496184", # CUP Terrains - Core
    "1562675299", # Winter Chernarus
]
parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
    "-world=empty",
]